// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajzqcptbwaadikefgycw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqenFjcHRid2FhZGlrZWZneWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDI2NzEsImV4cCI6MjA2ODQ3ODY3MX0.44s8mz3QJAdbkXBeOvG7QANhGTQn8ji-t_cKSB9X0tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});